### PR TITLE
Issue #11: Spell check on content added by user

### LINKED ISSUE #11: Spell check on content added by user
Be able to check that Experience, Education and Skill do not contain any spelling errors. This should be triggered by the user from the client. The format returned should follow this format:

```json
[
    {
        "before": "Hellq there",
        "after": "Hello there"
    }
]
```

If a better format can be found, this **must** be discussed with your Pod Leader to make sure the fellows contributing to the JavaScript repository can build functionality to match it.

This should include a test in `test_pytest.py` to show that it works correctly.

### PR DESCRIPTION
**Pull request by am831**
Implements spellchecking using the autocorrect lib. The user needs to trigger the /spellcheck endpoint with a POST request and specify the category and index as query parameters, for example: /spellcheck?category=experience&index=0

All misspelled words in the entry are updated by the spell_check_and_correct() function

Closes #11

### CODE REVIEW

**Comment by Buly1601** [comment]
image
"id" is not recognized, maybe the json has to have some ID?

**Comment by Buly1601** [comment]
weird error on ID, I think it's trying to access a json with the initial ID key there, will be skipping that error. Looks ready for merging

**Comment by am831** [comment]
Currently none of the tests work because the routes don't return an 'id' key in the JSON response when a POST request is made. I fixed it for experience(). But I realized that my implementation of POST in experience() is supposed to be #22. I think I should remove it from this PR and open it as #22

**Comment by am831** [comment]
Or we can close both #22 and #11 here

**Comment by am831** [comment]
I removed solution for #22 because Jocelyn said she already fixed it in another PR

**Pull request merged**
